#!/usr/bin/env python
import sys
import main
if(len(sys.argv) > 2):
    print("Too many arguments")
elif(len(sys.argv)<=1):
    print("aa-deactivate [profile]")
else:
    output = "Profile was successfully disabled."
    service = main.AppArmorService()
    service.disable_profile(sys.argv[1])
    print(output);
